// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["POSTGRES_URL"], // Direct PostgreSQL connection for migrations
    accelerateUrl: process.env["PRISMA_DATABASE_URL"], // Prisma Accelerate URL for queries
  },
});
